name: Publish NuGet package

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'netstandard2.0' 

      - name: Restore dependencies
        run: dotnet restore ./src/FluentDiagrams.NET/FluentDiagrams.NET.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore ./src/FluentDiagrams.NET/

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkgs

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
