name: Publish NuGet and GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ./src/FluentDiagrams.NET/FluentDiagrams.NET.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore ./src/FluentDiagrams.NET/

      - name: Pack
        run: dotnet pack ./src/FluentDiagrams.NET/FluentDiagrams.NET.csproj --configuration Release --no-build --output ./nupkgs

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $GITHUB_TOKEN --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
